[project]
name = "ocr-application"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "easyocr>=1.7.2",
    "opencv-python>=4.12.0.88",
    "pypdf2>=3.0.1",
    "reportlab>=4.4.5",
]
